### ISSUE TITLE
CPU Thermal Throttling

### ISSUE THREAD

**Issue by SulemanAhmadd** [TillmannBerg/Ubuntu-Dell-XPS-15-2019#1]
I followed the guide and successfully made all the tweaks on my new Dell XPS 15 7590 under a fresh install of ubuntu 19.04.

Since the past couple of todays I have noticed that the system starts to lag randomly and the fans start making noise.

After checking the logs, I found out that cpu thermal temperature was labeled as greater than the threshold value. It randomly fluctuates. Is their any proposed tweak for thermal throttling?

**Comment by Globegitter** [comment]
@SulemanAhmadd Not sure if this would help in your case but I did read that Ubuntu 19.10 with gnome 3.34 has apparently some performance improvements that should reduce CPU usage. Also from my own usage I have not heard the fan at al in the last couple of days.

**Comment by TillmannBerg** [comment]
Unfortunately, in the most recent Ubuntu 19.10 the suggestions about power management (and thus thermal throttling) do not seem to work anymore. At idle the power consumption remains at 25 W to 30 W. Could be the GPU, though.

Regarding the thermal warnings: That is actually hardware design and happens under Windows 10 as well.

**Comment by TillmannBerg** [comment]
I added a description for how to update/install the Nvidia GPU drivers. This greatly reduces the idle power consumption but breaks the standby functionality.
