### ISSUE TITLE
Wifi Driver Installation

### ISSUE THREAD

**Issue by EMH333** [TillmannBerg/Ubuntu-Dell-XPS-15-2019#2]
Hello,

On my laptop Ubuntu didn't detect the wifi card (a Killer AX1650 I believe) so I had to hunt around to find a solution. I found one at [their website](https://support.killernetworking.com/knowledge-base/killer-ax1650-in-debian-ubuntu-16-04/) but it isn't perfect. 

I would be happy to add a wifi driver section if you think it would be helpful?

**Comment by TillmannBerg** [comment]
If you want to write a wifi driver section, that would be very welcome. Just note that I have reverted back to using Windows on my machine (for now), so I cannot test this description myself.

**Comment by Globegitter** [comment]
@EMH333 Given that Ubuntu 19.10 is around the corner I would just recommend to only go with 19.10+ as the wifi works out of the box. I decided to reinstall using the 19.10 beta, and apart from the working wifi it also now includes the nvidia driver in the third party drivers. So far everything has been working really smoothly even though it is just a beta.

**Comment by TillmannBerg** [comment]
WiFi works out of the box with Ubuntu 19.10, but it presumably also works in Ubuntu 18.04.3 LTS, because this Ubuntu also has Linux kernel 5.3 now.
