### ISSUE TITLE
Display name

### ISSUE THREAD

**Issue by lrkwz** [TillmannBerg/Ubuntu-Dell-XPS-15-2019#4]
You can query for the display name sing

    xrandr --listmonitors | awk '$1 == "0:" {print $4}'

https://github.com/TillmannBerg/Ubuntu-Dell-XPS-15-2019/blob/85c988bdc6df1df23f1df801bd98e21b3c555674/dell-brightness.sh#L4

**Comment by KenEucker** [comment]
On a new XPS 15 7590:

When I run the command 
`xrandr --listmonitors | awk '$1 == "0:" {print $4}'`

I get the result

> `eDP-1-1` 

Changing this in the commands on the README worked, and this command does reduce the brightness 

`xrandr --output eDP-1-1 --brightness 0.6` 

However, the brightness buttons do not change the brightness. The path to the device is still `card0eDP-1`, but the dell-brightness.sh file does not work for me.

**Comment by lrkwz** [comment]
Did you create `/etc/acpi/events/dell-brightness-up` and `/etc/acpi/events/dell-brightness-down` to handle the key events as described in [README](https://github.com/TillmannBerg/Ubuntu-Dell-XPS-15-2019/blob/master/README.md)?

**Comment by KenEucker** [comment]
@lrkwz Yes I did. I followed every step in the README.

**Comment by lrkwz** [comment]
sorry, maybe @TillmannBerg can be of more help.
